name: Renovate update dependencies
on:
  schedule:
    # UTC 10:00 PM Sunday - Thursday (AEST 8:00 AM, Monday - Friday)
    - cron: "0 22 * * 0-4"
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
        env:
          RENOVATE_DRY_RUN: ${{ inputs.dry-run && 'full' || null }}
